## 練習時間
在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

#### Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家

### Hints: [隨機產生數值](https://blog.csdn.net/christianashannon/article/details/78867204)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# set 24 countries with random population
# population uses two random.rand to make it more realistic and rounded to integer
data = {'國家': ['Afhganistan', 'Brazil', 'Canada', 'Denmark', 'Ethiopia', 
               'Finland', 'Germany', 'Haiti', 'Iceland', 'Jamaica', 
               'Kenya', 'Liechtenstein', 'Monaco', 'Netherlands', 
               'Oman', 'Portugal', 'Qatar', 'Russia', 'Sweden', 
               'Taiwan', 'Uruguay', 'Vietnam', 'Yemen', 'Zimbabwe'],
        '人口': (np.random.rand(24) * np.random.rand(24) * 1000000000).astype(int)}
data = pd.DataFrame(data)
data

               國家         人口
0     Afhganistan  592447211
1          Brazil  741225440
2          Canada     407518
3         Denmark  693026791
4        Ethiopia  535525517
5         Finland  112658587
6         Germany  183980697
7           Haiti   73500988
8         Iceland  527787091
9         Jamaica  159862735
10          Kenya  268139612
11  Liechtenstein  202014877
12         Monaco  292276718
13    Netherlands  330016332
14           Oman   64240846
15       Portugal  505906292
16          Qatar  277325067
17         Russia  960807141
18         Sweden  107571375
19         Taiwan  517206750
20        Uruguay   11417905
21        Vietnam   48041998
22          Yemen  169395700
23       Zimbabwe   71555444

In [3]:
# the country with most population
data[data['人口'] == data['人口'].max()]

        國家         人口
17  Russia  960807141